// Curated preset pools, keyed by exact preset names from butterchurn-presets
// (base + extra packs). Names that fail to resolve at runtime are skipped.

// HYPE: hard-hitting, fast, beat-locked presets used when a drop is detected.
window.CURATED_HYPE = [
  'Flexi, martin + geiss - dedicated to the sherwin maxawow',
  'Flexi - mindblob [shiny mix]',
  'Flexi - mindblob mix',
  'flexi - Mindblob',
  'Flexi - smashing fractals [acid etching mix]',
  'Flexi - smashing fractals 2.0',
  '_Rovastar + Geiss - Hurricane Nightmare (Posterize Mix)',
  'Rovastar + Geiss - Hurricane Nightmare',
  'Rovastar + Flexi - Hurricane Nightmare (Moebius Mix)',
  'Goody - The Wild Vort',
  'martin - ludicrous speed',
  'martin - bring up the big guns',
  'martin - into the fireworks',
  'Martin - disco mix 6',
  'Martin - disco mix 3 -fast',
  'martin - disco mix 4',
  'martin - move this body',
  'martin - tunnel race',
  'martin - extreme heat',
  'Martin - acid wiring',
  'martin - cope - laser dome',
  'Geiss - Brain Zoom 4',
  'GreatWho - Lasershow',
  'Cope - The Neverending Explosion of Red Liquid Fire',
  'Eo.S. - glowsticks v2 05 and proton lights (+Krash′s beat code) _Phat_remix02b',
  'flexi - bouncing balls [double mindblob neon mix]',
  'Flexi + Geiss - Tokamak mindblob 2.0',
  'Flexi, fishbrain, Geiss + Martin - tokamak witchery',
  'Rovastar - Explosive Minds',
  'Flexi - crush ice 72',
  'PieturP - triptrap_(ultimate-trip-mix)',
  'EVET - RGB Singularity',
  'Stahlregen & Boz + Eo.S + Geiss + Phat + Rovastar + Zylot - Machine Code [Jelly]',
];

// FLOW: hypnotic, beautiful, slower presets for steady grooves between drops.
window.CURATED_FLOW = [
  'Aderrasi - Potion of Spirits',
  'Aderrasi - Songflower (Moss Posy)',
  'martin - angel flight',
  'cope + martin - mother-of-pearl',
  'Eo.S. + Zylot - skylight (Stained Glass Majesty mix)',
  'Flexi - infused with the spiral',
  'flexi - swing out on the spiral',
  'Geiss - Spiral Artifact',
  'Geiss - Myriad Mosaics',
  'martin - frosty caves 2',
  'martin - castle in the air',
  'martin - ghost city',
  'martin - glass corridor',
  'martin - satellite view',
  'Martin - journey into space',
  'Rovastar - A Million Miles From Earth (Wormhole Mix)',
  'Unchained & Rovastar - Wormhole Pillars (Hall of Shadows mix)',
  "TonyMilkdrop - Magellan's Nebula [Flexi - you enter first + multiverse]",
  'yin - 191 - Temporal singularities',
  'Zylot - Paint Spill (Music Reactive Paint Mix)',
  'ORB - Pastel Primer',
  'martin - reflections on black tiles',
  'Geiss - Reaction Diffusion 2',
  'Krash + Illusion - Spiral Movement',
];
